### ISSUE TITLE
Sdílení článku na FB nefunguje

### ISSUE THREAD

**Issue by JanSuchanek** [pirati-web/praha12.pirati.cz#162]
https://praha12.pirati.cz/aktuality/petice-proti-zahustovani-kamyku.html

Zkuste dát sdílet.

**Comment by janadamec1** [comment]
nechápu, čím to je. Pouzivame standardni theme, kde je to v /layouts/post.html, a tam je absoluteurl stejně jako jinde, na lokále mi to dělá adresy začínající http://localhost, ale p5ri nasazeni to neni absolutni. Zahada

**Comment by janadamec1** [comment]
Vyřešeno updatem theme.
